#!/bin/bash
source /usr/share/yunohost/helpers

# Get arguments
domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
admin=$YNH_APP_ARG_ADMIN
app=$YNH_APP_INSTANCE_NAME

# Create directory
final_path=/var/www/$app
mkdir -p $final_path

# Copy sources
cp -a ../sources/* $final_path/

# Setup nginx
ynh_add_nginx_config

# Setup SSO
ynh_permission_create --permission="main" --url="/" --allowed="$admin"

echo "Installation complete!"